--# description: full reorganization of kandoo menus, changing chars to Nchars
--# dependencies:
--# tables list: invoicehead
--# author: huho
--# date: 2019-03-22
--# Ticket # :
--# more comments: full reorganization of kandoo menus, changing chars to Nchars

--UNLOAD TO unl/invoicehead.unl SELECT * FROM invoicehead;
drop table invoicehead;

create table "informix".invoicehead 
(
cmpy_code char(2),
cust_code nvarchar(8),
org_cust_code nvarchar(8),
inv_num integer,
ord_num integer,
purchase_code nvarchar(30),
job_code nvarchar(8),
inv_date date,
entry_code nvarchar(8),
entry_date date,
sale_code nvarchar(8),
term_code nchar(3),
disc_per decimal(6,3),
tax_code nchar(3),
tax_per decimal(6,3),
goods_amt decimal(16,2),
hand_amt decimal(16,2),
hand_tax_code nchar(3),
hand_tax_amt decimal(16,2),
freight_amt decimal(16,2),
freight_tax_code nchar(3),
freight_tax_amt decimal(16,2),
tax_amt decimal(16,2),
disc_amt decimal(16,2),
total_amt decimal(16,2),
cost_amt decimal(16,2),
paid_amt decimal(16,2),
paid_date date,
disc_taken_amt decimal(16,2),
due_date date,
disc_date date,
expected_date date,
year_num smallint,
period_num smallint,
on_state_flag char(1),
posted_flag char(1),
seq_num smallint,
line_num smallint,
printed_num smallint,
story_flag char(1),
rev_date date,
rev_num smallint,
ship_code nvarchar(8),
name_text nvarchar(30),
addr1_text nvarchar(30),
addr2_text nvarchar(30),
city_text nvarchar(20),
state_code nvarchar(6),
post_code nvarchar(10),
country_text nvarchar(40),
ship1_text nvarchar(60),
ship2_text nvarchar(60),
ship_date date,
fob_text nchar(20),
prepaid_flag char(1),
com1_text nvarchar(30),
com2_text nvarchar(30),
cost_ind nchar(1),
currency_code nchar(3),
conv_qty float,
inv_ind nchar(1),
prev_paid_amt decimal(16,2),
acct_override_code nvarchar(18),
price_tax_flag char(1),
contact_text nvarchar(30),
tele_text nvarchar(20),
invoice_to_ind nchar(1),
territory_code nvarchar(5),
mgr_code nvarchar(8),
area_code nvarchar(5),
cond_code nchar(3),
scheme_amt decimal(16,2),
jour_num integer,
post_date date,
carrier_code nchar(3),
manifest_num integer,
bill_issue_ind nchar(1),
contract_code nchar(10),
stat_date date,
country_code nchar(3),
tax_cert_text nvarchar(15),
ref_num integer
);

LOAD FROM unl20190322/invoicehead.unl INSERT INTO invoicehead;
