--# description: full reorganization of kandoo menus, changing chars to Nchars
--# dependencies:
--# tables list: customer
--# author: huho
--# date: 2019-03-22
--# Ticket # :
--# more comments: full reorganization of kandoo menus, changing chars to Nchars

--UNLOAD TO unl/customer.unl SELECT * FROM customer;
drop table customer;

create table "informix".customer 
(
cmpy_code char(2),
cust_code nchar(8),
corp_cust_code nchar(8),
name_text nvarchar(30),
addr1_text nvarchar(30),
addr2_text nvarchar(30),
city_text nvarchar(20),
state_code nvarchar(20),
post_code nvarchar(16),
country_text nvarchar(40),
country_code nchar(3),
language_code nchar(3),
type_code nchar(3),
sale_code nchar(8),
term_code nchar(3),
tax_code nchar(3),
inv_addr_flag char(1),
sales_anly_flag char(1),
credit_chk_flag char(1),
setup_date date,
last_mail_date date,
tax_num_text nvarchar(15),
contact_text nvarchar(30),
tele_text nvarchar(20),
cred_limit_amt decimal(16,2),
cred_bal_amt decimal(16,2),
bal_amt decimal(16,2),
highest_bal_amt decimal(16,2),
curr_amt decimal(16,2),
over1_amt decimal(16,2),
over30_amt decimal(16,2),
over60_amt decimal(16,2),
over90_amt decimal(16,2),
onorder_amt decimal(16,2),
inv_level_ind nchar(1),
dun_code nchar(3),
bank_acct_code nvarchar(20),
delete_flag char(1),
delete_date date,
show_disc_flag char(1),
consolidate_flag char(1),
cond_code nchar(3),
pay_ind nchar(1),
hold_code nchar(3),
share_flag char(1),
scheme_amt decimal(16,2),
invoice_to_ind nchar(1),
ref1_code nvarchar(10),
ref2_code nvarchar(10),
ref3_code nvarchar(10),
ref4_code nvarchar(10),
ref5_code nvarchar(10),
ref6_code nvarchar(10),
ref7_code nvarchar(10),
ref8_code nvarchar(10),
mobile_text nvarchar(20),
ord_text_ind nchar(1),
corp_cust_ind nchar(1),
acn_text nchar(15),
cred_override_ind nchar(1),
comment_text nvarchar(60),
inv_reqd_flag char(1),
cred_reqd_flag char(1),
mail_reqd_flag char(1),
inv_format_ind nchar(1),
cred_format_ind nchar(1),
avg_cred_day_num smallint,
last_inv_date date,
last_pay_date date,
next_seq_num integer,
partial_ship_flag char(1),
back_order_flag char(1),
currency_code nchar(3),
int_chge_flag char(1),
stmnt_ind nchar(1),
ytds_amt decimal(16,2),
mtds_amt decimal(16,2),
ytdp_amt decimal(16,2),
mtdp_amt decimal(16,2),
late_pay_num smallint,
cred_given_num decimal(10),
cred_taken_num decimal(10),
fax_text nvarchar(20),
interest_per decimal(6,3),
territory_code nvarchar(5),
billing_ind nchar(1),
abn_text nvarchar(11)
);

LOAD FROM unl20190322/customer.unl INSERT INTO customer;
