set QX_WORKSPACE=H:\\Eclipse\\git
set PERLUTLDIR=%QX_WORKSPACE%\\KandooERP\\KandooERP\\Resources\\Utilities\\Perl
set PERLUTLINCL=%PERLUTLDIR%\\incl
set FFGDIR=%PERLUTLDIR%\\Ffg
set FFGINCLDIR=%PERLUTLINCL%
set FFGDATADIR=%QX_WORKSPACE\\KandooERP\\DBschema
set FGLLIBDIR=%FFGDIR%\\fgllib